name: srec_codec
description: Dart library to parse and write motorola SREC
version: 0.0.3-dev
author: Ravi Teja Gudapati <tejainece@gmail.com>
homepage: https://github.com/tejainece/srec_codec
documentation:

executables:
  view2srec:

environment:
  sdk: '>=1.20.0 <2.0.0'

dependencies:
  args: ^0.13.7

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
